Update Quiz Page
acmcsufoss/acmcsuf.com pull request #1059
Opened 2024-04-10 06:01 UTC by 26samaahmed

Fix #1052 
<img width="1440" alt="Screenshot 2024-04-09 at 10 56 43 PM" src="https://github.com/EthanThatOneKid/acmcsuf.com/assets/111910374/fd6b32ad-f982-41cf-a75c-c1e310d329d8">

2024-04-12 00:01 UTC, EthanThatOneKid requested changes
Some nitpicks:

### Color of button on results page looks weird in dark mode

![image](https://github.com/EthanThatOneKid/acmcsuf.com/assets/31261035/05137b51-4def-4989-abdc-99f289c23813)

### Gaps between team tiles could be increased horizontally and vertically

![image](https://github.com/EthanThatOneKid/acmcsuf.com/assets/31261035/ed0851e4-4302-4bd9-a0b7-7a15156227d3)

### Update results title to include "Quiz" e.g. "Quiz Results"

### Add 10% to Open Source Software team results

2024-04-12 05:58 UTC, JustinStitt commented on src/routes/(site)/quiz/quiz.svelte
> +    <p><i>What team are you a part of?</i></p>
nit: s/What/Which

I think that reads a bit better.

2024-04-12 06:00 UTC, JustinStitt commented
Your PR description says "Fix https://github.com/EthanThatOneKid/acmcsuf.com/issues/1052" but https://github.com/EthanThatOneKid/acmcsuf.com/issues/1052 mentions updating more than just the UI: `We need to update the data along with doing a redesign to fit with the style of the rest of the website.`

I think a bit more detail in your PR descriptions can help reviewers understand what is going on. With that being said, and with Ethan's review, you're on the right track 👍 🦖

2024-04-16 21:34 UTC, 26samaahmed commented
I have fixed the buttons on the results page as well as increase the gap between the team tile. I also noticed that the progress bar for some teams disappears on mobile so I increased the padding for the team tiles to be responsive.

<img width="300" alt="Screenshot 2024-04-16 at 2 22 33 PM" src="https://github.com/EthanThatOneKid/acmcsuf.com/assets/111910374/eea039db-7f07-4c1d-aa30-fff7847c1b22">  <img width="300" alt="Screenshot 2024-04-16 at 2 30 30 PM" src="https://github.com/EthanThatOneKid/acmcsuf.com/assets/111910374/2e74f0b9-d68d-4a8e-aace-242e82f5005e">


<img width="1440" alt="Screenshot 2024-04-16 at 2 21 38 PM" src="https://github.com/EthanThatOneKid/acmcsuf.com/assets/111910374/69425dcf-03f7-4622-8912-f5e3bec62c46">

<img width="847" alt="Screenshot 2024-04-16 at 2 23 56 PM" src="https://github.com/EthanThatOneKid/acmcsuf.com/assets/111910374/36e78c72-8906-4c20-91c0-39f30aa5339a">

2024-04-22 18:32 UTC, karnikaavelumani commented
## TODO
- [ ] Choice boxes should be a set size 
![image](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/2a6d791a-0d8c-429a-983e-9c2318381aea)
- [ ] Change the color of the choice boxes to be a darker color so the words pop out more (maybe it could be `var(--acm-blue)` while the buttons are `var(--acm-bluer)`
- [ ] Remove glow effect and replace with a solid border on hover
![image](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/896e667f-56aa-4c58-b384-d65cd699183c)
- [ ] Remove the general team, marketing team, special events team, and nodebuds team in the final results
![image](https://github.com/EthanThatOneKid/acmcsuf.com/assets/60043611/605d0bd7-4b99-4789-ab06-220946189ff1)

2024-04-30 06:01 UTC, 26samaahmed commented
For removing general, marketing, nodebuds, and special events team tiles from quiz results, the only way I was able to remove them is by deleting them from the teams.json since that's where we're getting the data from. Is there another way to remove them without affecting the rest of the website or modifying the teams.json file? @karnikaavelumani @EthanThatOneKid

2024-04-30 06:07 UTC, 26samaahmed commented
I removed the glow effect on hover and replaced it with a border color. I also changed the background color to be more readable and made the height fixed.

![Screenshot 2024-04-29 230433](https://github.com/EthanThatOneKid/acmcsuf.com/assets/111910374/8f848bb6-ac6f-4c3a-b876-416c2a4159da)

![Screenshot 2024-04-29 230523](https://github.com/EthanThatOneKid/acmcsuf.com/assets/111910374/459d7432-173c-4e18-8d12-cc4d34807062)

2024-05-02 05:08 UTC, EthanThatOneKid commented on src/routes/(site)/quiz/quiz.svelte
> +  // Bug in this definition
TODO(@EthanThatOneKid): Fix this lol.

2024-05-02 06:58 UTC, EthanThatOneKid commented on requirements.txt
Python moment

2024-05-02 20:53 UTC, EthanThatOneKid commented on src/routes/(site)/quiz/quiz.svelte
> +  // Bug in this definition
Resolved in <https://github.com/EthanThatOneKid/acmcsuf.com/pull/1059/commits/fcbc9fe8ab4c23dae9939c151dfc9d496ea2edaa>.

2024-05-03 00:11 UTC, karnikaavelumani approved these changes
LGTM!

2024-05-03 00:11 UTC, EthanThatOneKid approved these changes

2024-05-03 00:15 UTC, merged