Update Sitemap Page Design
acmcsufoss/acmcsuf.com pull request #1069
Opened 2024-04-21 21:10 UTC by 26samaahmed

Fix #1049 

I updated the design on the page and made it responsive across mobile as well.
<img width="1440" alt="Screenshot 2024-04-21 at 1 58 03 PM" src="https://github.com/EthanThatOneKid/acmcsuf.com/assets/111910374/e3dddf82-66c6-4931-901e-dd18e8100fa3">
<img width="321" alt="Screenshot 2024-04-21 at 1 58 34 PM" src="https://github.com/EthanThatOneKid/acmcsuf.com/assets/111910374/b658be26-b698-418f-ae60-60eeeaa5a5c2">

2024-04-21 21:28 UTC, EthanThatOneKid requested changes

2024-04-21 21:28 UTC, EthanThatOneKid commented on src/lib/public/sitemap/sitemap.ts
> +export type SiteMap = {
Run `npm run all` to automatically resolve any formatting errors.

2024-04-21 22:48 UTC, EthanThatOneKid commented on src/lib/public/sitemap/sitemap.ts
> +export type SiteMap = {
Resolved in <https://github.com/EthanThatOneKid/acmcsuf.com/pull/1069/commits/a51a7c94da5aef6b80cdedc39e86ef9147876a12>.

2024-04-21 22:49 UTC, EthanThatOneKid approved these changes
LGTM, @26samaahmed!

2024-04-21 22:50 UTC, EthanThatOneKid commented
This looks gr8!

2024-04-21 22:58 UTC, merged

2024-04-22 02:31 UTC, karnikaavelumani commented
Thank you @26samaahmed and @tylermlui for helping on this page!