Add ICPC logo to homepage
acmcsufoss/acmcsuf.com pull request #1142
Opened 2024-10-27 06:45 UTC by Peterchauu

Fix 1115:

- Added 'ICPC' team to the homepage
- Sorted all of the teams alphabetically
- Added an additional third row of team members to compensate for new teams

![feat-1115](https://github.com/user-attachments/assets/5523520e-2908-4b86-bcdc-05d02e0aaf45)

2024-10-27 20:33 UTC, Peterchauu commented
- Shortened ICPC Title

![image](https://github.com/user-attachments/assets/ea9b0ad7-34a5-43b5-a25b-8b4871351c94)

2024-10-27 22:04 UTC, 26samaahmed requested changes
All looks good. I think we should re-word the description a bit.

2024-10-27 22:04 UTC, 26samaahmed commented on src/routes/(site)/teams.svelte
> +            >Ready for a challenge? Scratch your competitive itch at the <span class="acm-orange"
```suggestion
            >Ready for a challenge? Scratch your competitive itch with the <span class="acm-orange"
```

2024-10-27 22:04 UTC, 26samaahmed commented on src/routes/(site)/teams.svelte
> +              >ICPC</span
```suggestion
              >ICPC Team</span
```

2024-10-28 00:10 UTC, Peterchauu commented
- Changed the description of the ICPC team

![image](https://github.com/user-attachments/assets/59992b5b-807c-402c-bf82-986ec0efd6bc)

2024-12-02 06:43 UTC, 26samaahmed commented
Perfect! Everything looks good for now, we will work on adding the Node buds logo once the Design Team Finalizes it! Nice job @Peterchauu 👏

2024-12-02 06:44 UTC, 26samaahmed approved these changes
Perfect! Everything looks good for now, we will work on adding the Node buds logo once the Design Team Finalizes it! Nice job @Peterchauu 👏

2024-12-02 06:44 UTC, merged