Modify acm-select.svelte to create a custom select dropdown
acmcsufoss/acmcsuf.com pull request #156
Opened 2021-10-23 23:16 UTC by anhduy1202

Hi, can you check the design as well as the code for my custom select dropdown? Thanks

2021-10-23 23:47 UTC, EthanThatOneKid requested changes
The component itself looks nice! I added some requests and comments for you.

2021-10-23 23:47 UTC, EthanThatOneKid commented on src/lib/components/utils/acm-select.svelte
> +	export let defaultValue: string | HTMLInputElement = '';
What is the `HTMLInputElement` type used for here?

2021-10-23 23:47 UTC, EthanThatOneKid commented on src/lib/components/utils/acm-select.svelte
> +	let option: HTMLDivElement;
This element acts as a container for the option elements, we could use a different name like `optionsContainer` or something along those lines.

2021-10-23 23:47 UTC, EthanThatOneKid commented on src/lib/components/utils/acm-select.svelte
> +	const setDrop = () => {
Nitpicking here, but let's rename this function to `openDropdown` to be more clear about what this event handler is called for.

2021-10-23 23:47 UTC, EthanThatOneKid commented on src/lib/components/utils/acm-select.svelte
> +		option.classList.toggle('active');
To open the dropdown menu, we do not need to manually toggle the class, but instead we can set a variable (maybe `active`) to true. Then, using that variable, you can conditionally use the CSS class like so: `<div class:active>...</div>` (more info on <https://svelte.dev/docs#class_name>).

2021-10-23 23:47 UTC, EthanThatOneKid commented on src/lib/components/utils/acm-select.svelte
> +						id={optionValue} />
This input element is not needed, so we can just use a normal DIV here; preferably the one that starts on line 24. This DIV can steal the `on:click={() => handleOption(optionValue)}` attribute and can use `{optionValue}` as the content of the DIV.

2021-10-23 23:47 UTC, EthanThatOneKid commented on src/lib/components/utils/acm-select.svelte
> +		defaultValue = term;
The body of this function can be refactored. A good start would be to create a new variable to store the current value (something like `currentValue`). It can be instantiated using the `defaultValue` near the top of the file, but should store the value as it is changed/updated/selected in this function.

2021-10-24 02:13 UTC, anhduy1202 commented on src/lib/components/utils/acm-select.svelte
> +	export let defaultValue: string | HTMLInputElement = '';
oh I forgot to delete it from a previous fix, done btw

2021-10-24 02:15 UTC, anhduy1202 commented on src/lib/components/utils/acm-select.svelte
> +	let option: HTMLDivElement;
done :)

2021-10-24 02:24 UTC, anhduy1202 commented on src/lib/components/utils/acm-select.svelte
> +						id={optionValue} />
I set the div class name as optionChoice, is that clear enough? also do you want to be refactor anything from the SCSS or it's good enough?

2021-10-24 02:25 UTC, anhduy1202 commented on src/lib/components/utils/acm-select.svelte
> +	const setDrop = () => {
done!

2021-10-24 02:39 UTC, anhduy1202 commented on src/lib/components/utils/acm-select.svelte
> +		option.classList.toggle('active');
this what I've done, it works so far ( line 23 )
```svelte
class={active ? 'option active' : 'option'}
```

2021-10-24 02:45 UTC, anhduy1202 commented on src/lib/components/utils/acm-select.svelte
> +		defaultValue = term;
can you elaborate more about the use of currentValue? is it storing the value of optionValue?

2021-10-24 02:50 UTC, anhduy1202 commented on src/lib/components/utils/acm-select.svelte
> +	let option: HTMLDivElement;
acutally, I was able to delete the optionContainer due to adding the active variables + using class from Svelte

2021-10-24 02:50 UTC, EthanThatOneKid commented on src/lib/components/utils/acm-select.svelte
> +		option.classList.toggle('active');
That does work technically but there might be an even better way depending on how you look at it.

I think this snippet is nice since it utilizes the `class:*` directive: `<div class="option" class:active>...</div>`.

2021-10-24 02:55 UTC, EthanThatOneKid commented on src/lib/components/utils/acm-select.svelte
> +		defaultValue = term;
The `currentValue` variable would store the value of `term` when a new term is chosen. You can initialize the variable at the top of the file like so:

```ts
let currentValue = defaultValue;
```

Then, you can use `currentValue` throughout the file to render the currently selected value.

2021-10-24 03:16 UTC, EthanThatOneKid commented on src/lib/components/utils/acm-select.svelte
> +						id={optionValue} />
That's a good name for the class, but for CSS naming we try to use kabob-case e.g. `option-choice`. 

As for the SCSS, I'll add more comments soon.

2021-10-24 04:06 UTC, anhduy1202 commented on src/lib/components/utils/acm-select.svelte
> +		defaultValue = term;
done!

2021-10-24 04:06 UTC, anhduy1202 commented on src/lib/components/utils/acm-select.svelte
> +						id={optionValue} />
done!

2021-10-24 04:07 UTC, anhduy1202 commented on src/lib/components/utils/acm-select.svelte
> +		option.classList.toggle('active');
done!

2021-10-24 04:17 UTC, diamondburned commented on src/lib/components/utils/acm-select.svelte
> +	const setDrop = () => {
> Nitpicking here, but let's rename this function to `openDropdown` to be more clear about what this event handler is called for.

It would be more correct to call this function `toggleDropDown`, since it
doesn't actually set it to open when called twice.

2021-10-24 04:21 UTC, EthanThatOneKid commented on src/lib/components/utils/acm-select.svelte
> +	const setDrop = () => {
I didn't think of having the button toggle the action variable which is a nice touch by @anhduy1202. With this in mind, I agree that the verb "toggle" does work better in the function name as @diamondburned said.

2021-10-24 04:25 UTC, anhduy1202 commented on src/lib/components/utils/acm-select.svelte
> +	const setDrop = () => {
@EthanThatOneKid  sounds great! did you check my recent PR? besides from this renaming, any comments on the fix I made? thanks

2021-10-24 04:31 UTC, EthanThatOneKid commented on src/lib/components/utils/acm-select.svelte
> +	const setDrop = () => {
I'll reply with any comments I have in a future change request :)

2021-10-24 05:05 UTC, EthanThatOneKid requested changes
I added a few more nitpicks with some more notes on the CSS. Keep up the great work; this is becoming a pretty solid Svelte component!

2021-10-24 05:05 UTC, EthanThatOneKid commented on src/lib/components/utils/acm-select.svelte
> +	const openDropdown = () => {
> It would be more correct to call this function toggleDropdown, since it doesn't actually set it to open when called twice.

Mentioned in <https://github.com/EthanThatOneKid/acmcsuf.com/pull/156#discussion_r735060397>.

2021-10-24 05:05 UTC, EthanThatOneKid commented on src/lib/components/utils/acm-select.svelte
> +				color: transparent;
The color can be set to `var(--acm-light)` since the background color is set to `var(--acm-dark)`.

2021-10-24 05:05 UTC, EthanThatOneKid commented on src/lib/components/utils/acm-select.svelte
>  	}
I think the `.radio` selector is currently unused.

2021-10-24 05:05 UTC, EthanThatOneKid commented on src/lib/components/utils/acm-select.svelte
> +	let dropTitle: HTMLDivElement;
I think the `dropTitle` variable is unused.

2021-10-24 05:05 UTC, EthanThatOneKid commented on src/lib/components/utils/acm-select.svelte
> +		border-radius: 6px 6px 0px 0px;
I was thinking that maybe we could keep all the corners rounded, except when the element is active. One way this can be done is by moving `class:active` from line 23 to the `.option-box` DIV. Then in the CSS, you can do something along the lines of...

```css
.selected {
  border-radius: 6px;
}

.active > .selected {
  border-radius: 6px 6px 0px 0px;
}
```

This change implies that the selector on line 73 must be adjusted as well. From `.option.active` to `.active > .option`.

2021-10-24 17:22 UTC, anhduy1202 commented on src/lib/components/utils/acm-select.svelte
> +	let dropTitle: HTMLDivElement;
done!

2021-10-24 17:24 UTC, anhduy1202 commented on src/lib/components/utils/acm-select.svelte
> +	const openDropdown = () => {
done!

2021-10-24 17:27 UTC, anhduy1202 commented on src/lib/components/utils/acm-select.svelte
> +				color: transparent;
done!

2021-10-25 01:10 UTC, anhduy1202 commented on src/lib/components/utils/acm-select.svelte
>  	}
done!

2021-10-25 01:18 UTC, anhduy1202 commented on src/lib/components/utils/acm-select.svelte
> +		border-radius: 6px 6px 0px 0px;
done!

2021-10-25 01:27 UTC, EthanThatOneKid approved these changes
This solid, 88-lined custom select component looks good to me! Feel free to squash and merge your PR whenever you're ready, @anhduy1202.

2021-10-25 01:30 UTC, merged