Resolved annoying 'css-unused-selector' warning messages
acmcsufoss/acmcsuf.com pull request #333
Opened 2022-03-12 10:17 UTC by EthanThatOneKid

- Deleted `theme.scss` file
- Made each component responsible for their own `rfs` style
- Removed `gfm.css` (GitHub Flavored Markdown) CSS library

Resolves #332.

2022-03-13 19:39 UTC, mikeploythai approved these changes
rfs package doesn't resize some headers to become smaller on mobile breakpoint like before, but tbh i kinda like it. approved

![image](https://user-images.githubusercontent.com/54593375/158076136-0c1ab822-751f-4313-83cc-e160dd3fea28.png)

2022-03-13 20:25 UTC, MohamedHabarneh approved these changes

2022-03-15 00:53 UTC, EthanThatOneKid commented
> rfs package doesn't resize some headers to become smaller on mobile breakpoint like before, but tbh i kinda like it. approved

I added the RFS-generated values to our `global.css` since we don't need to recalculate them.

### Updated Screenshot

![image](https://user-images.githubusercontent.com/31261035/158284453-7a6a40dd-6790-4b1e-9238-fb6598927d2b.png)

2022-03-15 16:52 UTC, ghost requested changes
Join button text should be a big larger for desktop
![image](https://user-images.githubusercontent.com/54593375/158430095-33b86b64-cafc-46d9-a00e-8944d68cd5a3.png)

Hover on join button is different now. The background color should be changing to acmBlue, not the text color.

2022-03-16 05:39 UTC, merged