SvelteKit release candidate migration: about page
acmcsufoss/acmcsuf.com pull request #541
Opened 2022-09-11 00:51 UTC by EthanThatOneKid

- Copied over the required Svelte for the about page
- Refactored repeated code
- Resolved TypeScript errors

2022-09-20 17:23 UTC, k4rni requested changes
Great start:) Now fix it.

2022-09-20 17:23 UTC, k4rni commented on src/lib/public/board/data/tiers.json
> +[
Tiers need to be updated (src/lib/public/board/data/officers.json should reflect these tiers)

2022-09-20 17:23 UTC, k4rni commented on src/lib/public/board/utils.ts
> +  termIndex: number
Rename this to "index" to avoid conflicts with termIndex variable name

2022-09-20 17:23 UTC, k4rni commented on tests/test.ts
> +
no way this is so cool

2022-09-21 16:08 UTC, EthanThatOneKid commented on src/lib/public/board/utils.ts
> +  termIndex: number
This nit can be addressed in a future refactor.

2022-09-21 16:08 UTC, EthanThatOneKid commented on src/lib/public/board/data/tiers.json
> +[
The tiers indeed must be updated. This can be done in a future PR.

2022-09-21 16:10 UTC, EthanThatOneKid commented on tests/test.ts
> +
Playwright tests are great! Related: #557.

2022-09-21 16:11 UTC, karnikaavelumani approved these changes
This looks very sexy

2022-09-22 02:52 UTC, EthanThatOneKid commented
Replaced by mega-PR #577.

2022-09-22 02:52 UTC, closed without merging