Use full names for blog post authors
acmcsufoss/acmcsuf.com pull request #601
Opened 2022-10-07 05:05 UTC by Peekoe

Resolves #488

I removed officer since it doesn't work for anyone currently

2022-10-07 05:18 UTC, EthanThatOneKid commented
> I removed officer since it doesn't work for anyone currently

I think that the officer images regression occurred after a recent PR (maybe #597). 

Side note: Screenshot testing would allow us to catch unintended changes in other pages earlier. Related: #557.

2022-10-15 05:27 UTC, jaasonw requested changes

2022-10-15 05:27 UTC, jaasonw commented on src/lib/server/blog/posts.ts
> +// function getOfficerByGhUsername(ghUsername: string): Officer | null {
seem to work now for some reason, but not exactly, maybe look into fixing this or just commit to removing it entirely?

![image](https://user-images.githubusercontent.com/8981287/195970464-778246c2-fb24-4b93-9115-66dde7da42c9.png)

2022-10-30 00:07 UTC, Peekoe commented
lol the officer data already works, we just don't have it. non board members will not have full names displayed to avoid API calls

2022-10-30 00:07 UTC, closed without merging