Add Rohan Kunchala to the about page!
acmcsufoss/acmcsuf.com pull request #632
Opened 2022-10-23 08:51 UTC by EthanThatOneKid

Welcome, Rohan!
![Rohan](https://github.com/EthanThatOneKid/acmcsuf.com/raw/b63791c31e9539a731c3aebbbd56d4392dc78d0c/static/assets/authors/rohan-kunchala.webp)

2022-10-23 10:48 UTC, jaasonw requested changes
screenshjot is broekn

![image](https://user-images.githubusercontent.com/8981287/197387851-001be115-95d6-4390-a77b-85244a36ce92.png)

2022-10-23 10:52 UTC, jaasonw requested changes
picture should be 459 x 459, currently is 485 x 485, upon further inspection, alan's photo is also not correctly size

![image](https://user-images.githubusercontent.com/8981287/197388020-cc528f2b-6cd9-4827-a382-e66cc772da25.png)

2022-10-24 03:51 UTC, AlanCortez1337 commented
After what seemed like 12 years, my badge's dimensions are correct I triple checked it. The issue I'm starting to see is that the people with the card social feature Diamond made are affected by this. Unless I have literally gone insane, look closer at Ethan's, Diamond's and my badges compared to the others who do not have their socials connected yet.
![badge card interaction](https://user-images.githubusercontent.com/78040578/197444929-a13b40b2-bcc8-41e3-beaa-bc47152d816b.PNG)

2022-10-26 20:22 UTC, jaasonw approved these changes

2022-10-26 20:22 UTC, merged