I added a circle to the confetti, I think
acmcsufoss/acmcsuf.com pull request #672
Opened 2022-11-04 22:31 UTC by JHMuir

2022-11-05 18:44 UTC, EthanThatOneKid requested changes
There is only a minor change keeping you from saying, "first try 😎", but luckily it is a super minor change needed to make your SVG file valid. I left a suggestion in my review, feel free to commit the suggestion directly or add it manually if you have additional changes :).

2022-11-05 18:44 UTC, EthanThatOneKid commented on static/assets/1st/circle-thing.svg
> +<circle cx="25" cy="75" r="20"/>
> [Hi did I do it right?](https://github.com/EthanThatOneKid/acmcsuf.com/pull/672/commits/359c23a02aa36ea30a0baf54e815cd063d25e1d4)

You were close!

SVG files must begin with a root tag of `svg`.

```suggestion
<svg width="50" height="50" viewBox="0 0 50 50" fill="#2c91c6" xmlns="http://www.w3.org/2000/svg">
  <circle cx="25" cy="25" r="25"/>
</svg>
```

2022-11-06 06:43 UTC, jaasonw commented
Also for future reference, your pull requests should contain the following
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/8981287/200157980-450a5a3d-6b38-4394-9411-5a268e68e20e.png">

2022-11-07 23:13 UTC, EthanThatOneKid approved these changes
Nice first contribution!

2022-11-07 23:14 UTC, merged