Adding meta tag for blog post
acmcsufoss/acmcsuf.com pull request #693
Opened 2022-11-08 11:50 UTC by anhduy1202

# Description
- I've added meta tag for blog post such that if user copy paste blog link, it should display a preview

# Note:
- I've installed a package  [svelte-meta-tags](https://github.com/oekazuma/svelte-meta-tags) according to Svelte recommendation that help displaying the meta tag 

# Screenshots:

<img width="464" alt="Screen Shot 2022-11-08 at 3 48 54 AM" src="https://user-images.githubusercontent.com/58461444/200556614-c8c9cc3c-c4d3-4791-b12c-e8c4368b9c2e.png">

2022-11-08 12:10 UTC, anhduy1202 commented
look like the DOMParser() caused the 500 error thar fail website check, will fix it tmr

2022-11-08 19:51 UTC, EthanThatOneKid requested changes
Thanks for kicking off this initiative. Can't wait to see relevant blog content before clicking on the blog post URL. I recommend removing issue #525 from this PR since here we are specifically implementing text meta tags as to resolve #692. Thoughts on making a separate PR to resolve #525?

2022-11-08 19:51 UTC, EthanThatOneKid commented on src/routes/(site)/blog/[id]/blog-body.svelte
> +/>
`MetaTags` usage in `src/routes/(site)/blog/[id]/blog-body.svelte` may be redundant as it is already in use on the page endpoint `src/routes/(site)/blog/[id]/+page.svelte`.

2022-11-08 19:51 UTC, EthanThatOneKid commented on src/routes/(site)/blog/[id]/+page.svelte
> +      authors: [`${data.post.author.url}`],
Unless I am missing something, the template literals are optional.
```suggestion
    title: data.post.title,
    url: data.post.url,
    type: 'article',
    article: {
      publishedTime: data.post.createdAt,
      modifiedTime: data.post.lastEdited,
      authors: [data.post.author.url],
```

2022-11-08 19:51 UTC, EthanThatOneKid commented on src/routes/(site)/blog/[id]/+page.svelte
>    export let data: PageData;
Nit: Leave a space between the imports and the exports.
```suggestion
  import { MetaTags } from 'svelte-meta-tags';

  export let data: PageData;
```

2022-11-09 05:16 UTC, anhduy1202 commented
# Update
- I just refactored. deleted DOMParser() and use existed query from Github instead 

# Note
I have to use string literals here since the allowed type is string | undefined form 'svelte-meta-tag' while the existing type of data.post.lastEdited is string | null
```js
modifiedTime: `${data.post.lastEdited}`,
```

# Screenshot
<img width="737" alt="Screen Shot 2022-11-08 at 9 16 26 PM" src="https://user-images.githubusercontent.com/58461444/200744763-38837471-5f8a-4fff-bbc8-3fb6042ffee9.png">

2022-11-09 22:31 UTC, anhduy1202 commented on src/routes/(site)/blog/[id]/blog-body.svelte
> +/>
done

2022-11-09 22:31 UTC, anhduy1202 commented on src/routes/(site)/blog/[id]/+page.svelte
> +      authors: [`${data.post.author.url}`],
done

2022-11-09 22:31 UTC, anhduy1202 commented on src/routes/(site)/blog/[id]/+page.svelte
>    export let data: PageData;
done

2022-11-09 22:49 UTC, jaasonw requested changes
u cant hide from me

2022-11-09 22:49 UTC, jaasonw commented on src/lib/components/blog/blog-post-preview.svelte
> -
why?

2022-11-09 22:49 UTC, jaasonw commented on src/routes/(site)/blog/[id]/blog-body.svelte
> -
why?

2022-11-09 22:49 UTC, jaasonw commented on src/routes/(site)/blog/[id]/+page.svelte
> +    description: description,
not seem to work, can you look into why?

![image](https://user-images.githubusercontent.com/8981287/200957751-77e98b5c-fb36-4f78-a3b6-572f9df5a946.png)

2022-11-09 22:49 UTC, jaasonw commented on src/lib/public/blog/types.ts
> +  bodyText?: string;
how come mark optional?

2022-11-09 22:52 UTC, anhduy1202 commented on src/lib/public/blog/types.ts
> +  bodyText?: string;
cause it's not required, we only need that for meta tag

2022-11-10 09:15 UTC, anhduy1202 commented on src/lib/public/blog/types.ts
> +  bodyText?: string;
done, it's required now

2022-11-10 10:02 UTC, EthanThatOneKid requested changes
Preview looks good on Discord so far!

![0136CBB7-94BB-426E-87BF-E9C67E478986](https://user-images.githubusercontent.com/31261035/201061463-2c6c6d3c-781c-4cf6-882e-8facf3fc2eaa.jpeg)

2022-11-10 10:02 UTC, EthanThatOneKid commented on src/routes/(site)/blog/[id]/blog-body.svelte
> -
Nit: Undo changes in `src/routes/(site)/blog/[id]/blog-body.svelte`.

2022-11-10 10:02 UTC, EthanThatOneKid commented on src/lib/server/blog/posts.ts
> +      bodyText: bodyText,
Nit: Redundant destructor. 
```suggestion
      bodyText,
```

2022-11-10 10:02 UTC, EthanThatOneKid commented on src/lib/server/blog/data.ts
>  export const SAMPLE_BLOG_POSTS = [
Move JSON content below to a separate JSON file. Import it here with proper type checking.

2022-11-10 10:02 UTC, EthanThatOneKid commented on src/lib/components/blog/blog-post-preview.svelte
>    import Labels from '$lib/components/blog/labels.svelte';
Nit: Remove changes in `src/lib/components/blog/blog-post-preview.svelte`.

2022-11-10 10:02 UTC, EthanThatOneKid commented on src/routes/(site)/blog/[id]/+page.svelte
> +    description: description,
Nit: Move description definition to the MetaTag initialization. Related: Truncate to the last index of a space character `‘  ‘` or place there be ellipses at the end of the truncated description string.

2022-11-10 13:23 UTC, jaasonw commented on src/routes/(site)/blog/[id]/+page.svelte
> +        alt: `photo of ${data.post.author.fullname}`,
capitalize p

2022-11-10 17:46 UTC, anhduy1202 commented on src/routes/(site)/blog/[id]/+page.svelte
> +        alt: `photo of ${data.post.author.fullname}`,
tf

2022-11-11 07:52 UTC, anhduy1202 commented on src/routes/(site)/blog/[id]/+page.svelte
> +        alt: `photo of ${data.post.author.fullname}`,
done

2022-11-11 07:56 UTC, anhduy1202 commented on src/routes/(site)/blog/[id]/blog-body.svelte
> -
done

2022-11-11 07:57 UTC, anhduy1202 commented on src/lib/server/blog/posts.ts
> +      bodyText: bodyText,
done

2022-11-11 07:57 UTC, anhduy1202 commented on src/lib/components/blog/blog-post-preview.svelte
>    import Labels from '$lib/components/blog/labels.svelte';
done

2022-11-11 07:59 UTC, anhduy1202 commented on src/routes/(site)/blog/[id]/+page.svelte
> +    description: description,
done

2022-11-11 08:10 UTC, anhduy1202 commented on src/lib/server/blog/data.ts
>  export const SAMPLE_BLOG_POSTS = [
done

2022-11-11 16:17 UTC, EthanThatOneKid approved these changes
> ![3D807148-7492-4872-8780-E782AF9428D6](https://user-images.githubusercontent.com/31261035/201383770-fca0185b-da5d-46ed-b4f8-4eea5c710822.jpeg)

LGTM!

2022-11-11 20:01 UTC, jaasonw approved these changes
ur so sexy for that

2022-11-11 20:03 UTC, merged