Fix title behind navbar
acmcsufoss/acmcsuf.com pull request #815
Opened 2023-03-15 14:18 UTC by nghuyhoang0204

Hey i've checked this issue and i think the problem is about the margin-top in CSS of this page so i've added and here is the result 
<img width="1440" alt="Screenshot 2023-03-15 at 01 04 22" src="https://user-images.githubusercontent.com/99657702/225336968-ac38407b-d257-42c5-a89f-f16f1a075bb9.png">

2023-03-15 19:14 UTC, karnikaavelumani requested changes
Thank you so much for submitting your code changes! I respect your view of simplicity when it comes to this issue. However, adding a specific value for padding can lead to inconsistent and unpredictable results making it harder to reapproach this page in the future for changes.

Instead, we should focus on centering the content itself. While I appreciate your efforts to improve the layout, I think we need to take a more deliberate approach to ensure that the content is centered correctly.

In order to achieve this, I recommend that you take a look at the HTML and consider putting the content in the `section` tag into a `div` tag so that it will be easy to center
<img width="975" alt="image" src="https://user-images.githubusercontent.com/60043611/225417709-feae5eca-6b31-4a2c-95ff-331175a96bcb.png">

From there you should try to see if it is possible to center it without any numeric values for the sake of preventing brute forced programming.

2023-03-15 19:41 UTC, EthanThatOneKid reviewed
> Instead, we should focus on centering the content itself.

The suggestion to center the 404 page content in a new DIV is a valid heuristic. 

Note: The DIV might need a height >100vh since a height of 100vh might be too small.

2023-03-15 23:32 UTC, nghuyhoang0204 commented
Okayy i see what i have to do for this issue . Thanks for your review and detail suggestion
. Ill try to make another Pr 😸

2023-03-16 05:55 UTC, EthanThatOneKid commented
> . Ill try to make another Pr 😸

You don’t have to make a new PR, this one is fine too.

2023-03-20 00:03 UTC, nghuyhoang0204 commented
Hello guys , so i've made a few changes to this code sorry if my codes are not clean , please check it and give me comment if i have to fix anything else

2023-03-20 06:22 UTC, EthanThatOneKid requested changes
> please check it and give me comment if i have to fix anything else

Nice! I left a few comments.

2023-03-20 06:22 UTC, EthanThatOneKid commented on src/lib/components/button/button.svelte
The `src/lib/components/button/button.svelte` component isn't within the scope of this PR. Undo any changes in this file.

2023-03-20 06:22 UTC, EthanThatOneKid commented on src/routes/+error.svelte
> +  /* section {
Nit: Delete unused comments.

2023-03-20 10:06 UTC, nghuyhoang0204 commented on src/lib/components/button/button.svelte
Hello , if i undo these changes of this file button , the result will be like this 
<img width="1440" alt="Screenshot 2023-03-20 at 00 02 39" src="https://user-images.githubusercontent.com/99657702/226308129-669b6b65-48b8-4d14-9c86-af51a46f3bee.png">
Do you still accepte

2023-03-20 20:35 UTC, karnikaavelumani commented
![image](https://user-images.githubusercontent.com/60043611/226459744-504aa7ed-b4b6-4294-b467-3c6169671c77.png)
I would take just a look again because a change of yours actually affected the landing page!

2023-03-20 22:06 UTC, EthanThatOneKid commented on src/lib/components/button/button.svelte
> Do you still accepte

I would try to fix the undesired width by putting the button in a container with a set width.

2023-03-20 23:30 UTC, nghuyhoang0204 commented
Okay guys , i see what i've done so this is my newest commit for yours changes requested . I hope it will be fine now 😄 
<img width="1440" alt="Screenshot 2023-03-20 at 01 04 07" src="https://user-images.githubusercontent.com/99657702/226487601-00fbaf3d-d65d-48f3-a3cb-ab2f20ccd18a.png">

2023-03-21 00:08 UTC, EthanThatOneKid requested changes
Your PR looks good so far. I left a few more comments for you to consider.

2023-03-21 00:08 UTC, EthanThatOneKid commented on src/lib/components/button/button.svelte
> +
Nit: Remove unused linebreak.

2023-03-21 00:08 UTC, EthanThatOneKid commented on src/routes/+error.svelte
> +    height: 120vh;
I thought that giving the section a height of >100vh would do the trick. It is close, but not exactly what we need.

What we could do is simply add back your technique from earlier by setting padding to the top of the container to offset the space left under the navbar.

With this offset `padding-top: 100px`, we may remove `height: 120vh` _in favor of the existing `min-height: 100vh`_.

```suggestion
    padding-top: 100px;
```

2023-03-21 00:08 UTC, EthanThatOneKid commented on src/routes/+error.svelte
> +    text-shadow: rgb(146, 196, 223) 2px 2px;
Nit: Use available CSS variable.
```suggestion
    text-shadow: var(--acm-blue) 2px 2px;
```

2023-03-21 00:15 UTC, nghuyhoang0204 commented
I am very happy to follow your requests

2023-03-21 00:53 UTC, EthanThatOneKid approved these changes
LGTM! 🎉 

Thank you for another contribution, @nghuyhoang0204!

2023-03-21 00:54 UTC, EthanThatOneKid commented on src/routes/+error.svelte
> +    text-shadow: rgb(146, 196, 223) 2px 2px;
Resolved in <https://github.com/EthanThatOneKid/acmcsuf.com/pull/815/commits/af5cc8fd621356f807183cc4db231fe192b041d4>.

2023-03-21 00:54 UTC, EthanThatOneKid commented on src/routes/+error.svelte
> +    height: 120vh;
Resolved in <https://github.com/EthanThatOneKid/acmcsuf.com/pull/815/commits/af5cc8fd621356f807183cc4db231fe192b041d4>.

2023-03-21 00:54 UTC, EthanThatOneKid commented on src/lib/components/button/button.svelte
> +
Resolved in <https://github.com/EthanThatOneKid/acmcsuf.com/pull/815/commits/af5cc8fd621356f807183cc4db231fe192b041d4>.

2023-03-21 00:54 UTC, EthanThatOneKid commented on src/routes/+error.svelte
> +  /* section {
Resolved in <https://github.com/EthanThatOneKid/acmcsuf.com/pull/815/commits/f1cb7fb2574a82a88b7e0f7038a0c15013fe9b91>.

2023-03-21 00:58 UTC, EthanThatOneKid commented on src/lib/components/button/button.svelte
Resolved in <https://github.com/EthanThatOneKid/acmcsuf.com/pull/815/commits/f1cb7fb2574a82a88b7e0f7038a0c15013fe9b91>.

2023-03-21 01:00 UTC, nghuyhoang0204 commented
With my pleasure , thanks for your reviews and your comments 🤓🤩

2023-03-21 01:01 UTC, karnikaavelumani approved these changes
LGTM! Great job:)

2023-03-21 01:03 UTC, merged