769
acmcsufoss/acmcsuf.com pull request #821
Opened 2023-03-28 20:46 UTC by jiink

2023-03-28 21:34 UTC, EthanThatOneKid commented on scripts/transform-genuary/in.json
> +
Nit: Rogue empty line.

2023-03-28 21:34 UTC, EthanThatOneKid commented on scripts/transform-genuary/test-data.json
> +
Nit: Rogue empty line.

2023-03-28 21:56 UTC, EthanThatOneKid commented on scripts/transform-genuary/in.json
> +
Resolved in <https://github.com/EthanThatOneKid/acmcsuf.com/pull/821/commits/034a277d3a450c1ef240c226f96fb4029c5c4375>.

2023-03-28 21:56 UTC, EthanThatOneKid commented on scripts/transform-genuary/test-data.json
> +
Resolved in <https://github.com/EthanThatOneKid/acmcsuf.com/pull/821/commits/034a277d3a450c1ef240c226f96fb4029c5c4375>.

2023-03-29 00:10 UTC, EthanThatOneKid approved these changes
Excited to finally see `.github/workflows/update_genuary.yaml` in prod!

2023-03-29 00:13 UTC, EthanThatOneKid requested changes
Oh no!!

![image](https://user-images.githubusercontent.com/31261035/228394348-b4614d26-7b0f-4cb9-9874-0c7ac3fc1af4.png)

2023-03-29 00:47 UTC, EthanThatOneKid requested changes

2023-03-29 00:47 UTC, EthanThatOneKid commented on .github/workflows/check_website.yaml
> +          fi
Apologies, I missed this syntax error in my previous review. This text is multiline.

```suggestion
        run: |
           if git diff --exit-code --quiet scripts/transform-genuary; then
             echo "updated=0" >> $GITHUB_OUTPUT;
           else
             echo "updated=1" >> $GITHUB_OUTPUT;
           fi
```

2023-03-29 03:12 UTC, EthanThatOneKid approved these changes

2023-03-29 03:15 UTC, merged

2023-03-29 03:16 UTC, EthanThatOneKid commented
Keep an eye out for <https://acmcsuf.com/code/actions/workflows/update_genuary.yaml> on March 29th, 2023! 👀

2023-03-29 19:10 UTC, jiink reviewed
Looks good!