about page dropdown
acmcsufoss/acmcsuf.com pull request #842
Opened 2023-04-26 10:47 UTC by JustinStitt

### Fix dropdown behavior

## Old Behavior
![dropdown-old](https://user-images.githubusercontent.com/24460581/234552208-206e507f-18bb-45f3-8e81-d1f251e6bb96.gif)
**notice the jumps and ability to click __invisible__ options!**

## New Behavior
![dropdown](https://user-images.githubusercontent.com/24460581/234552097-427dedcd-fa53-48b2-b83e-dbe4678f8b71.gif)
**much nicer 😄**

### Also added new on hover effect for team members
![hover1](https://user-images.githubusercontent.com/24460581/234552535-6c912107-50ef-457b-809a-d95892ad6c8e.gif)

2023-04-26 11:00 UTC, jaasonw requested changes

2023-04-26 11:00 UTC, jaasonw commented on src/lib/components/select/select.svelte
> +    {#if active === true}
not pep8 compliant

2023-05-03 10:19 UTC, jjoeldaniel commented on src/lib/components/select/select.svelte
> +    {#if active === true}
fixed [here](https://github.com/EthanThatOneKid/acmcsuf.com/pull/842/commits/d05b4998f300e967101fceacfd7cbd221dd2113a)

2023-05-03 10:24 UTC, jaasonw requested changes, later dismissed

2023-05-03 10:24 UTC, jaasonw commented on src/routes/(site)/wave1/+page.svelte
> +    if (expanded === true) positions.forEach((el) => el.removeAttribute('open'));
nortt pep8 compilkert

2023-05-03 10:26 UTC, jjoeldaniel commented on src/routes/(site)/wave1/+page.svelte
> +    if (expanded === true) positions.forEach((el) => el.removeAttribute('open'));
resolved [here](https://github.com/EthanThatOneKid/acmcsuf.com/pull/842/commits/2ae8197a84e81263754fb19d6fbcc088778b0255)

2023-05-03 10:39 UTC, jjoeldaniel approved these changes
lgtm - the j's

2023-05-03 10:47 UTC, merged

2023-05-03 11:15 UTC, jaasonw commented
ur a stale revirew

2023-05-03 19:26 UTC, k4rni commented
Thank you for catching this and for the PR.

Make sure to check what files you're committing next time because you pushed some changes into prod that weren't approved yet!