share blog button
acmcsufoss/acmcsuf.com pull request #847
Opened 2023-05-09 02:32 UTC by barrotbake

Resolves #684 
👽🤟

2023-05-11 09:59 UTC, jaasonw requested changes

2023-05-11 09:59 UTC, jaasonw commented on src/lib/components/blog/blog-post-preview.svelte
> +          ev.preventDefault();
prefer using svelte event modifier
![image](https://github.com/EthanThatOneKid/acmcsuf.com/assets/8981287/bb15b2ea-b41f-4003-b6a4-31417c9e9e03)

2023-05-11 09:59 UTC, jaasonw commented on src/lib/components/blog/blog-post-preview.svelte
> +    color: var(--text-color);
button should prob have
a. `cursor: pointer;` on hover
b. a border similar to the event page
c. a hover effect similar to that of the event page

https://github.com/EthanThatOneKid/acmcsuf.com/assets/8981287/30def6d7-1941-412f-aef7-8e9f961dedc3

2023-05-11 09:59 UTC, jaasonw commented on src/lib/components/blog/blog-post-preview.svelte
> +            "https://acmcsuf.com/" + makeBlogPostPageUrl(post.id),
avoid hard coding the url here, the current url can be accessed with `window.location.href` or `document.URL`
![image](https://github.com/EthanThatOneKid/acmcsuf.com/assets/8981287/c8fa8a3f-3d3f-419d-9e69-575532ee0bef)

2023-05-11 09:59 UTC, jaasonw commented on src/lib/components/blog/blog-post-preview.svelte
> +            'general'
this parameter is optional and doesn't really need to be here

2023-05-11 19:31 UTC, caretcakejake commented on src/lib/components/blog/blog-post-preview.svelte
> +            'general'
you mean line 36?

2023-05-11 22:02 UTC, jaasonw commented on src/lib/components/blog/blog-post-preview.svelte
> +            'general'
i mean line 37, "general"

2023-05-11 22:12 UTC, barrotbake commented on src/lib/components/blog/blog-post-preview.svelte
> +    color: var(--text-color);
LMAOO not the snapchat record 💀 
>  Snapchat-1326091595.mp4

2023-05-11 22:31 UTC, barrotbake commented on src/lib/components/blog/blog-post-preview.svelte
> +            'general'
This makes the toast popup blue which makes sense and Karni liked it

2023-05-11 23:18 UTC, jaasonw commented on src/lib/components/blog/blog-post-preview.svelte
> +            'general'
it was blue when i tested it without but I can double check

2023-05-12 01:59 UTC, barrotbake commented on src/lib/components/blog/blog-post-preview.svelte
> +    color: var(--text-color);
No the button looks fine. No highlights 😠

2023-05-12 02:03 UTC, barrotbake commented on src/lib/components/blog/blog-post-preview.svelte
> +            "https://acmcsuf.com/" + makeBlogPostPageUrl(post.id),
is done

2023-05-13 04:22 UTC, jaasonw approved these changes
yes

2023-05-23 06:24 UTC, EthanThatOneKid commented
@barrotbake The reason the check failed for this PR is because of a formatting error. This can be resolved by committing the changes made after running `npm run format`. Can you let me know if you'd like me to go ahead and format and then merge the PR?

2023-05-30 23:37 UTC, barrotbake commented
Hey @EthanThatOneKid yeah you can go ahead and run it and merge. Thanks so much!

2023-05-31 00:08 UTC, EthanThatOneKid approved these changes
LGTM 😎

2023-05-31 00:12 UTC, merged