Update dev team section.
acmcsufoss/acmcsuf.com pull request #957
Opened 2023-11-09 03:31 UTC by 26samaahmed

<img width="1440" alt="Screen Shot 2023-11-08 at 7 29 18 PM" src="https://github.com/EthanThatOneKid/acmcsuf.com/assets/111910374/222d2067-1754-412a-9d3f-b2415fd82d54">
Fix #951

2023-11-12 05:35 UTC, EthanThatOneKid requested changes
Nice, small PR! Please see my comment for a suggestion regarding user preferences.

2023-11-12 05:35 UTC, EthanThatOneKid commented on src/routes/(site)/6/teams/team-section.svelte
> +
Let's disable the animations in the case that a user prefers reduced motion.[^1]

```suggestion
@media (prefers-reduced-motion: reduce) {
  .dev-animation img {
    animation: none;
  }
}
```

> The setting is used to convey to the browser on the device that the user prefers an interface that removes, reduces, or replaces motion-based animations.
 Such animations can trigger discomfort for those with [vestibular motion disorders](https://www.a11yproject.com/posts/understanding-vestibular-disorders/).[^2]

[^1]: https://web.dev/articles/prefers-reduced-motion#working_with_the_media_query_from_css_and_javascript_contexts
[^2]: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

2023-11-12 21:10 UTC, 26samaahmed commented
I added your suggestion!!

2023-11-13 06:50 UTC, EthanThatOneKid approved these changes
This PR looks good to go! Nice work, @26samaahmed.

2023-11-13 23:08 UTC, merged