Update Testimony Component
acmcsufoss/acmcsuf.com pull request #984
Opened 2023-11-29 23:32 UTC by 26samaahmed

<img width="1419" alt="Screen Shot 2023-11-29 at 3 30 48 PM" src="https://github.com/EthanThatOneKid/acmcsuf.com/assets/111910374/18d53250-e672-41d1-bb80-0b369c359cc2">
fix #980

2023-12-03 04:04 UTC, EthanThatOneKid approved these changes
LGTM 👍

2023-12-05 23:37 UTC, karnikaavelumani requested changes

2023-12-05 23:37 UTC, k4rni commented on src/routes/(site)/6/testimony.svelte
> +    font-size: 20px;
You got the right idea! But instead of using arbitrary numbers, can you take a look at the `global.css` file and see what preset sizes we have for the fonts? ex.) `font-size: var(--size-sm);`

2023-12-06 07:06 UTC, 26samaahmed commented on src/routes/(site)/6/testimony.svelte
> +    font-size: 20px;
Got it, I will go ahead and fix that!

2023-12-06 07:22 UTC, 26samaahmed commented
<img width="1417" alt="Screen Shot 2023-12-05 at 11 17 58 PM" src="https://github.com/EthanThatOneKid/acmcsuf.com/assets/111910374/d79927f1-ca46-4dc2-b1bb-aace0e6a58b1">

2023-12-07 21:54 UTC, EthanThatOneKid commented on src/routes/(site)/6/testimony.svelte
> +    font-size: 20px;
Sama resolved in <https://github.com/EthanThatOneKid/acmcsuf.com/pull/984/commits/e257c27506f59f9e79718903a145a744a97227dc> 😎

2023-12-07 22:52 UTC, k4rni approved these changes
LGTM!

2023-12-07 22:52 UTC, merged